---
title: "Bad Drivers Report"
author: "Franceska Padilla Coo"
date: "October 9, 2022"
output:
  html_document:
    toc: TRUE
    theme: lumen
    toc_depth: 3
    code_folding: show
    toc_float: TRUE
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

```

```{r}
library(tidyverse)
```

```{r}
bad_drivers <- read_csv('bad-drivers.csv')
```

```{r}
bad_drivers['state_areas'] <- c(50750, 570641, 113642, 52075, 155973, 103730, 4845, 1955, 68.32, 53997, 57919, 6423, 82751, 55593, 35870, 55875, 81823, 39732, 43566, 30865, 9775, 7838, 56539, 79617, 46914, 68898, 145556, 76878, 109806, 8969, 7419, 121365, 47224, 48718, 68994, 40953, 68679, 96003, 44820, 1034, 30111, 75898, 41220, 261914, 83168, 9249, 39598, 66582, 24087, 54314, 97105)
colnames(bad_drivers)
```
```{r}
states_w_regions <- read_csv('us_states_w_regions.csv')
states_w_regions <- states_w_regions[order(states_w_regions$State), ]
bad_drivers['regions'] <- states_w_regions['Region']
bad_drivers['state_code'] <- states_w_regions['State Code']
```

```{r}
question1 <- ggplot(bad_drivers, aes(x=`Number of drivers involved in fatal collisions per billion miles`*10^4, y=state_areas, color=regions))+
  geom_point()+
  geom_smooth(method='lm',se=FALSE)+
  geom_text(aes(label= ifelse(state_areas > quantile(state_areas, 0.95),
     as.character(State),'')),hjust=0,vjust=0)+
  labs(title='Western Region Has More Area (miles) per State and Collisions', 
       x='Number of Drivers Involved in Fatal Collisions per 1000 Miles', 
       y='State Areas in Miles')

question1
```

```{r}
ggsave('CollisionsAndStateArea', plot=question1, device='png')
```

```{r}
question2 <- ggplot(bad_drivers, aes(x=`Losses incurred by insurance companies for collisions per insured driver ($)`, y=`Car Insurance Premiums ($)`, color=regions))+
  geom_point()+
  geom_smooth(method='lm', se=FALSE)
  
question2
```

```{r}
ggsave('PremiumsAndLosses', plot=question2, device='png')
```

```{r}
question3 <- ggplot(bad_drivers, aes(x=state_code, y=`Number of drivers involved in fatal collisions per billion miles`))+
  geom_col(aes(fill=regions))+
  scale_x_discrete(guide = guide_axis(n.dodge=3))+
  labs(title='Number of fatal Collisions per Billion Miles per State', x='State Code')
  
  
question3
```
```{r}
ggsave('AccidentsVSState', plot=question3, device='png')
```




